# render.yaml
services:
  - type: web
    name: new-cv-backend    env: docker
    dockerfilePath: ./BackEnd/Dockerfile
    dockerContext: ./BackEnd
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: new-cv-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  - name: new-cv-db
    databaseName: new_cv
    plan: free
