"""Add missing analysis types to enum

Revision ID: ff6e661ae333
Revises: c3ebe11d3eae
Create Date: 2025-06-01 13:53:40.841039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6e661ae333'
down_revision: Union[str, None] = 'c3ebe11d3eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # For MySQL, we need to ALTER the column to add new enum values
    # MySQL doesn't support adding values to an existing ENUM, so we recreate it
    
    # First, change the column to VARCHAR temporarily
    op.execute("ALTER TABLE cv_analysis_history MODIFY COLUMN analysis_type VARCHAR(50)")
    
    # Now change it back to ENUM with all the values
    op.execute("""
        ALTER TABLE cv_analysis_history 
        MODIFY COLUMN analysis_type ENUM(
            'CV_WEAKNESS', 
            'JOB_MATCHING', 
            'CV_OPTIMIZATION',
            'CV_ANALYSIS',
            'JOB_DESCRIPTION_ANALYSIS'
        ) NOT NULL
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert back to original enum values
    op.execute("ALTER TABLE cv_analysis_history MODIFY COLUMN analysis_type VARCHAR(50)")
    
    op.execute("""
        ALTER TABLE cv_analysis_history 
        MODIFY COLUMN analysis_type ENUM(
            'CV_WEAKNESS', 
            'JOB_MATCHING', 
            'CV_OPTIMIZATION'
        ) NOT NULL
    """)
    
    # ### end Alembic commands ###
