name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Add this secret in your GitHub repository
          api-key: ${{ secrets.RENDER_API_KEY }} # Add this secret in your GitHub repository

      - name: Wait for deploy
        run: sleep 60 # Wait for deployment to complete

      - name: Verify deployment
        run: |
          echo "Checking deployment at ${{ secrets.RENDER_SERVICE_URL }}"
          curl -s -o /dev/null -w "%{http_code}" ${{ secrets.RENDER_SERVICE_URL }}/health | grep 200 || exit 1
